### ISSUE TITLE
Unable to install on Redmine 4.1.1.stable

### ISSUE THREAD

**Issue by Sir-Will** [neffets/redmine-stuff-to-do-plugin#14]
I'm getting the following error trying to run this plugin (master branch) on 4.1.1:

```
/home/redmine/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:5:in `<class:StuffToDoMailer>': undefined method `split' for nil:NilClass (NoMethodError)
        from /home/redmine/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:2:in `<top (required)>'
```

**Comment by neffets** [comment]
Its working on 4.2.1.stable.
Please try again
